Services:
  portainer:
    image: docker.io/portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /home/core/compose-files/portainer/data:/data:Z
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:ro
